### ISSUE TITLE
Question/feature: source-generator

### ISSUE THREAD

**Issue by GufNZ** [rluba/uniform#2]
C# recently added the ability to turn Regexes into generated sourcecode, which allows one to "compile" the expression into inserted source, which is then available to any optimisations the compiler wants to make, and is also stepable in the debugger.
The C# generated code is also nicely annotated with comments - I particularly like how generating from a regex that cannot match anything outputs an empty method with `// This can never match anything!` as its only content.

Is this something you/we might consider adding [later]?

**Comment by rluba** [comment]
If speed is important to you, I would recommend porting the more-specialized fast-path engines from the RE2 library (DFA, single-pass NFA, …) before trying a completely different approach.

I personally wouldn’t implement the source-code generation. But if that sounds promising and interesting to you, feel free to experiment with it and submit a PR.
